### Выполнение домашнего задания 1, содержащего в себе базовую работу с библиотекой NumPy

В файле `HW01.ipynb`:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [2]:
import numpy as np # Импорт библиотеки с общепринятым алиасом

In [7]:
array_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # создание массива из одномерного списка
print(f"NumPy массив из одномерного списка: {array_list}")

NumPy массив из списка: [ 1  2  3  4  5  6  7  8  9 10]


In [16]:
array_list = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # создание массива из двумерного списка
print(f"NumPy массив из двумерного списка: \n{array_list}")

NumPy массив из двумерного списка: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
array_list_1 = np.zeros((5)) # создание массива из нулей
array_list_2 = np.zeros((10, 10)) # создание массива из нулей
print(f"NumPy массив из списка нулей: {array_list_1}")
print(f"NumPy массив из списка нулей: \n{array_list_2}")

NumPy массив из списка нулей: [0. 0. 0. 0. 0.]
NumPy массив из списка нулей: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
array_list_1 = np.ones((5)) # создание массива из единиц
array_list_2 = np.ones((10, 10)) # создание массива из единиц
print(f"NumPy массив из списка единиц: {array_list_1}")
print(f"NumPy массив из списка единиц: \n{array_list_2}")

NumPy массив из списка единиц: [1. 1. 1. 1. 1.]
NumPy массив из списка единиц: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
range_array_1 = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
range_array_2 = np.arange(10)  # от 0 до 10
print(f"arange(0, 10, 2): {range_array_1}")
print(f"arange(5): {range_array_2}")

arange(0, 10, 2): [0 2 4 6 8]
arange(5): [0 1 2 3 4 5 6 7 8 9]


- Также массивы можно создавать из других python-коллекций: кортежа, множества
- Либо заполнить их с помощью других numpy методов: единичная матрица, диагональная матрица, с повторами

In [23]:
# Информация о массиве
print(f"Массив: \n{array_list}")
print(f"Форма массива: {array_list.shape}")
print(f"Тип данных: {array_list.dtype}")
print(f"Размерность: {array_list.ndim}")
print(f"Общее количество элементов: {array_list.size}")

Массив: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма массива: (3, 3)
Тип данных: int64
Размерность: 2
Общее количество элементов: 9


In [30]:
# Получение отдельного элемента
print(f"Первый элемент (индекс 0): {array_list[0]}")
print(f"Последний элемент (индекс -1): {array_list[-1]}")
print(f"Элемент с индексом 2: {array_list[2]}")
print(f"Элемент с индексом 0, 1: {array_list[0][1]}")

Первый элемент (индекс 0): [1 2 3]
Последний элемент (индекс -1): [7 8 9]
Элемент с индексом 2: [7 8 9]
Элемент с индексом 0, 1: 2


In [37]:
# Срезы
print(f"Срез [0:2]: \n{array_list[0:2]}")  # элементы с индексами 1, 2
print(f"Срез [:]: \n{array_list[:]}")    # все элементы
print(f"Срез [2]: {array_list[6:]}")    # элемент с индексом 2

Срез [0:2]: 
[[1 2 3]
 [4 5 6]]
Срез [:]: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Срез [2]: []


In [40]:
# Создаем два массива для операций
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([10, 20, 30, 40, 50])

print(f"Поэлементное сложение: A + B = {array_1 + array_2}")
print(f"Поэлементное умножение: A * B = {array_1 * array_2}")

Поэлементное сложение: A + B = [11 22 33 44 55]
Поэлементное умножение: A * B = [ 10  40  90 160 250]


In [42]:
print("Базовые статистические операции:")
print(f"Данные: {array_1 * array_2}")

print(f"Среднее значение (mean): {np.mean(array_1 * array_2)}")
print(f"Сумма всех элементов (sum): {np.sum(array_1 * array_2)}")
print(f"Минимальное значение (min): {np.min(array_1 * array_2)}")
print(f"Максимальное значение (max): {np.max(array_1 * array_2)}")
print(f"Стандартное отклонение (std): {np.std(array_1 * array_2):.2f}")
print(f"Медиана (median): {np.median(array_1 * array_2)}")

Базовые статистические операции:
Данные: [ 10  40  90 160 250]
Среднее значение (mean): 110.0
Сумма всех элементов (sum): 550
Минимальное значение (min): 10
Максимальное значение (max): 250
Стандартное отклонение (std): 86.49
Медиана (median): 90.0
